---
- name: Welcome to the RHCSA 9 Study/Test Environment!
  debug:
    msg:
      - ' The repo server, Server 1, and Server 2 have been set up successfully!'
      - '------------------------------------------------------------------------'
      - ' Servers 1 and 2 are rebooting.  If you are unable to access them right away,'
      - ' wait a couple moments, then try again.'
      - '------------------------------------------------------------------------'
      - ' Accessing The Systems:'
      - '- Repo - 192.168.55.149'
      - '- Server 1 - 192.168.55.150'
      - '- Server 2 - 192.168.55.151'
      - '- Username/Password - vagrant/vagrant or root/password'
      - '- Access example - `ssh root@192.168.55.150` or `vagrant ssh system1`'
      - ' -----------------------------------------------------------------------'
      - '- Two additional interfaces and drives are on Server 2.'
      - '- Happy Studying!'
